### PR TITLE
Support arbitrary push options

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by flaccid** [comment]
@eherot failing rubocop https://travis-ci.org/xhost-cookbooks/openvpn/jobs/57108559#L215. @jtimberman thoughts on this one?

**Comment by jtimberman** [comment]
I don't know that I'm too keen on the idea of extending `Chef::Mixin::Template` directly like this. I think what we want is a template helper, as [documented](https://docs.chef.io/resource_template.html#helpers).

**Comment by eherot** [comment]
Template helpers are a new concept to me, but they definitely look like a better way to do this. Making changes, brb.

**Comment by eherot** [comment]
How's this?

**Comment by flaccid** [comment]
I like, its a good step. Too much to ask for at least one test (chefspec or rspec)?

**Comment by eherot** [comment]
Not at all. My personal preference would be for ServerSpec (although I can add ChefSpec, too) if no one minds me adding that to this project.

**Comment by flaccid** [comment]
Any of the above is good. Sorry, in transit at Hungary airport atm. Cheers!

**Comment by eherot** [comment]
The ServerSpec tests I included will not actually run until #49 is addressed.

**Comment by flaccid** [comment]
@eherot https://github.com/xhost-cookbooks/openvpn/issues/49#issuecomment-90484890 can you see if you can update your tests based on 'server' as opposed to 'default'? Additionally there are a few minor rubocop issues to address (https://travis-ci.org/xhost-cookbooks/openvpn/jobs/57370658#L208).

**Comment by eherot** [comment]
Fixed the RuboCop issues. I'll go ahead and update the namespace for my tests but someone else is going to need to go through and fix the bats tests.

**Pull request merged**
