### PR TITLE
Support multiple options such as route using arrays

### PR DESCRIPTION
**Pull request by chewi**
I didn't touch the commented route/push stuff in the recipes. I don't think I'd want it to automatically add routes like this. I suggest we just remove that.

### CODE REVIEW

**Comment by chewi** [comment]
I just rebased this. I don't believe the test failure was my fault.

**Comment by flaccid** [comment]
This is now supported in recent changes.

**Comment by chewi** [comment]
I know you've already done the work but wasn't my suggestion very much simpler?

**Comment by flaccid** [comment]
@chewi No you are right, this is the right way to do multiple directives of the same key. My apologies, I have manually merged your enhancement in. Thank you.

**Comment by chewi** [comment]
Thanks. Is the push_routes and push_options stuff still needed then? There hasn't been a release yet so it wouldn't be unreasonable to remove it now.

**Comment by flaccid** [comment]
push routes and options: https://github.com/xhost-cookbooks/openvpn#attributes.
Its ok to support both methods, the push ones being like helpers.
So its possible to do something like this when we combine:

```
    attributes:
      openvpn:
        config:
          verb: 1
          mute: 10
          route:
           - '192.168.4.0 255.255.255.0'
           - '192.168.5.0 255.255.255.0'
          iroute:
           - '192.168.4.0 255.255.255.0'  
           - '192.168.5.0 255.255.255.0'
        push_routes:
          - 192.168.10.0 255.255.255.0
          - 10.12.10.0 255.255.255.0
        push_options:
          dhcp-option:
          - 'DOMAIN local'
          - 'DOMAIN-SEARCH local'
```

**Pull request closed without merging**
