### PR TITLE
allow to choose the cookbook for user's conf template

### PR DESCRIPTION
**Pull request by chrisduong**
Hi, 

We just need to add `cookbook` method with node's **attribute**, called `node['openvpn']['cookbook_user_conf']`, so with wrapper cookbook we can override to use our own _client.conf/ovpn template_.

### CODE REVIEW

**Comment by flaccid** [comment]
@chrisduong can you add some instructions to the readme on how to use this functionality for the use case?

**Comment by chrisduong** [comment]
@flaccid, I'm going to add this line to README. How do you feel about it
```
* `node['openvpn']['cookbook_user_conf']` - String. Default is 'openvpn', the recipe `openvpn::users` would use its own `client.conf.erb` template. You can override this to your own with your wrapper cookbook. 
```

**Comment by flaccid** [comment]
@chrisduong just minor edits:
* `node['openvpn']['cookbook_user_conf']` - String. The cookbook used by the `openvpn::users` recipe for the `client.conf.erb` template. You can override this to your own, such as your wrapper cookbook. Default is '`openvpn`'.

**Comment by chrisduong** [comment]
Ok, I've just pushed. :)

**Comment by flaccid** [comment]
Great, thanks!

**Pull request merged**
